### ISSUE TITLE
Ctrl-D triggers error

### ISSUE THREAD

**Issue by xiao-feng** [toivoh/Debug.jl#62]
At debug prompt, pressing Ctrl-D triggers repeating of 
debug:3> ParseError("end of input")
...
...

Also, readline doesn't seem to work on my installation -- up/down key produces weird char sequences.

Thank you for looking into it.

**Comment by toivoh** [comment]
Ok, I added a check for end of file before calling `readline`, which quits the debugging session.
It seems that the eof state of stdin is reset each time you return to the repl.
