### ISSUE TITLE
"invalid assignment location" when I use a form of for loop syntax

### ISSUE THREAD

**Issue by CCWRoy** [toivoh/Debug.jl#63]
Hey guys,

The following works:

    using Debug
    @debug function myfunc(x::Matrix)
        for n1=1:size(x)[1]
            for n2=1:size(x)[2]
                println(x[n1,n2]);
            end
        end
        @bp
        xx=1;
    end

The following doesn't work:

    @debug function myfunc2(x::Matrix)
        for n1=1:size(x)[1], n2=1:size(x)[2]
                println(x[n1,n2]);
        end
        
        xx=1;
    end

I get an error:
```ERROR: syntax: invalid assignment location```
 ```in include at ./boot.jl:245```
 ```in include_from_node1 at ./loading.jl:128```

I'm using Debug 0.0.4, and my versioninfo() is:

    Julia Version 0.3.1
    Commit c03f413 (2014-09-21 21:30 UTC)
    Platform Info:
      System: Linux (x86_64-linux-gnu)
      CPU: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G
      WORD_SIZE: 64
      BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY)
      LAPACK: liblapack.so.3
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

Thanks!

**Comment by kyle-pena-nlp** [comment]
Appreciate it Toivoh, and btw what a fantastic tool you've made.  It's become indispensable for me.

**Comment by toivoh** [comment]
Hmm, didn't mean for it to take quite so long, but should hopefully be fixed now. It was a bit trickier than I thought.

**Comment by toivoh** [comment]
Will update METADATA soon.

**Comment by CCWRoy** [comment]
Thank you, tolvoh!
