### ISSUE TITLE
Using @debug function func(x) results in  ERROR: T not defined

### ISSUE THREAD

**Issue by macd** [toivoh/Debug.jl#65]
Ubuntu 14.04
Version 0.4.0-dev+1330 (2014-10-28 03:56 UTC)
Commit 7fdc860* (0 days old master)
x86_64-linux-gnu

julia> using Debug

WARNING: deprecated syntax "{a for a in b}" at /home/ubuntu/.julia/v0.4/Debug/src/Analysis.jl:40.
Use "Any[a for a in b]" instead.
... and more deprecated syntax warnings (this is not the problem)
...
...  this is the problem
julia> @debug function square(x)
           return x*x
       end
ERROR: T not defined

julia> 

Doesn't seem like a usage error.

**Comment by toivoh** [comment]
I've opened the issue https://github.com/JuliaLang/julia/issues/10445 about the above error. We'll see how it plays out.

**Comment by toivoh** [comment]
Closed by https://github.com/toivoh/Debug.jl/commit/ebb4cc043ac95e1635eac8f6a2db095ced67bb19. Debug now seems to work on Julia 0.4.
