### ISSUE TITLE
Semicolon does not suppress output in debugger

### ISSUE THREAD

**Issue by mwojnowi** [toivoh/Debug.jl#66]
Hi, I am working on an algorithm that is run over 7 million variables.   When I use the Julia debugger, the semicolon fails to suppress output.

**Comment by toivoh** [comment]
Should be fixed now, I did a simple regex match to see if the input ends with a semicolon (possibly followed by whitespace). It's possible to trick it with comments and such, but I hope this should be enough for now. Will update METADATA soon.
